FROM fedora:29
%%%OS%%%
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN echo fubar > /etc/machine-id
%%%INSTALL_DEPENDENCIES_COMMAND%%%
RUN flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
RUN flatpak install flathub org.gnome.Sdk//3.30 -y
RUN flatpak install flathub org.gnome.Platform//3.30 -y
RUN mkdir /build
WORKDIR /build
COPY . .
CMD ["./contrib/ci/flatpak.py"]
